/**
 * @fileoverview ExecutionKernel interface — the core execution engine for Record-Replay V3.
 */

import type { JsonObject } from '../../domain/json';
import type { FlowId, NodeId, RunId } from '../../domain/ids';
import type { RRError } from '../../domain/errors';
import type { FlowV3 } from '../../domain/flow';
import type { DebuggerCommand, DebuggerState } from '../../domain/debug';
import type { RunEvent, RunStatus, Unsubscribe } from '../../domain/events';

/**
 * Request to start a new run.
 */
export interface RunStartRequest {
  /** Run ID (generated by the caller). */
  runId: RunId;
  /** Flow ID. */
  flowId: FlowId;
  /** Full flow snapshot used for this execution. */
  flowSnapshot: FlowV3;
  /** Run arguments. */
  args?: JsonObject;
  /** Start node ID (defaults to the flow's entryNodeId). */
  startNodeId?: NodeId;
  /** Tab ID (must be allocated by the caller; exclusive per run). */
  tabId: number;
  /** Debug configuration. */
  debug?: { breakpoints?: NodeId[]; pauseOnStart?: boolean };
}

/**
 * Final result of a run.
 */
export interface RunResult {
  /** Run ID. */
  runId: RunId;
  /** Terminal status. */
  status: Extract<RunStatus, 'succeeded' | 'failed' | 'canceled'>;
  /** Total elapsed time in milliseconds. */
  tookMs: number;
  /** Error (if failed). */
  error?: RRError;
  /** Output results. */
  outputs?: JsonObject;
}

/**
 * Run status query result.
 */
export interface RunStatusInfo {
  /** Current status. */
  status: RunStatus;
  /** Currently executing node ID. */
  currentNodeId?: NodeId;
  /** Start time. */
  startedAt?: number;
  /** Last updated time. */
  updatedAt: number;
  /** Tab ID. */
  tabId?: number;
}

/**
 * Core execution engine interface for Record-Replay V3.
 */
export interface ExecutionKernel {
  /**
   * Subscribe to the event stream.
   * @param listener Event listener
   * @returns Unsubscribe function
   */
  onEvent(listener: (event: RunEvent) => void): Unsubscribe;

  /**
   * Enqueue and start a run.
   */
  startRun(req: RunStartRequest): Promise<void>;

  /**
   * Pause a run.
   * @param runId Run ID
   * @param reason Pause reason
   */
  pauseRun(runId: RunId, reason?: { kind: 'command' }): Promise<void>;

  /**
   * Resume a paused run.
   * @param runId Run ID
   */
  resumeRun(runId: RunId): Promise<void>;

  /**
   * Cancel a run.
   * @param runId Run ID
   * @param reason Optional cancel reason
   */
  cancelRun(runId: RunId, reason?: string): Promise<void>;

  /**
   * Execute a debugger command.
   * @param runId Run ID
   * @param cmd Debugger command
   */
  debug(
    runId: RunId,
    cmd: DebuggerCommand,
  ): Promise<{ ok: true; state?: DebuggerState } | { ok: false; error: string }>;

  /**
   * Query run status.
   * @param runId Run ID
   * @returns Status info or null if the run does not exist
   */
  getRunStatus(runId: RunId): Promise<RunStatusInfo | null>;

  /**
   * Recover interrupted runs after a Service Worker restart.
   */
  recover(): Promise<void>;
}

/**
 * Create a stub ExecutionKernel that throws on every call.
 * Placeholder for Phase 0.
 */
export function createNotImplementedKernel(): ExecutionKernel {
  const notImplemented = () => {
    throw new Error('ExecutionKernel not implemented');
  };

  return {
    onEvent: () => {
      notImplemented();
      return () => {};
    },
    startRun: async () => notImplemented(),
    pauseRun: async () => notImplemented(),
    resumeRun: async () => notImplemented(),
    cancelRun: async () => notImplemented(),
    debug: async () => notImplemented(),
    getRunStatus: async () => notImplemented(),
    recover: async () => notImplemented(),
  };
}
